# ndarray.shape

# the dimension of the array. This is a tuple of integers indicating the size of the array in each dimension.
For matrix with n rows and m columns, shape will be (n, m). The length of the shape tuple is therefore the number of axes, ndim.

# ndarray.size

the total number of elements of the array. This is equal to the product of the elements of shape.

# ndarray.size

the total number of elements of the array. This is equal to the product of the elements of shape.

# ndarray.dtype

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

# ndarray.itemsize

the size in bytes of each element of the array.
For example, an array of elements of type float64 has 
itemsize 8 (=64/8), 
while one of type complex32 has itemsize 4 (=32/8). 
It is equivalent to ndarray.dtype. itemsize.

## ndarray.data

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.


In [16]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sn

In [29]:
num = np.arange(20).reshape(4, 5)

In [26]:
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
# Structure of the array
num.shape

(4, 5)

In [23]:
num.dtype

dtype('int64')

In [31]:
num.size

20

In [33]:
num.data

In [35]:
num.itemsize

8

# ARRAY
An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element

# Rank
The rank of the array is the number of dimensions.

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a_ = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [37]:
a 

array([1, 2, 3, 4, 5, 6])

In [38]:
a_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
print(a[0])

1


In [40]:
# Accessing elements in the array
print(a_[0][3])

4


In [ ]:
# An array can also be labelled as ndarray(N-dimensional array)
