# ndarray.shape

# the dimension of the array. This is a tuple of integers indicating the size of the array in each dimension.
For matrix with n rows and m columns, shape will be (n, m). The length of the shape tuple is therefore the number of axes, ndim.

# ndarray.size

the total number of elements of the array. This is equal to the product of the elements of shape.

# ndarray.dtype

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

# ndarray.itemsize

the size in bytes of each element of the array.
For example, an array of elements of type float64 has 
itemsize 8 (=64/8), 
while one of type complex32 has itemsize 4 (=32/8). 
It is equivalent to ndarray.dtype. itemsize.

## ndarray.data

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.


In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sn

In [2]:
num = np.arange(20).reshape(4, 5)

In [3]:
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
# Structure of the array
num.shape

(4, 5)

In [5]:
num.dtype

dtype('int64')

In [6]:
num.size

20

In [7]:
num.data

In [8]:
num.itemsize

8

# ARRAY
An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element

# Rank
The rank of the array is the number of dimensions.

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a_ = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [10]:
a 

array([1, 2, 3, 4, 5, 6])

In [11]:
a_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print(a[0])

1


In [13]:
# Accessing elements in the array
print(a_[0][3])

4


# An array can also be labelled as ndarray(N-dimensional array)
# Ndarray means any dimensional array

What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension. Numpy dimensions are AXES

In [15]:
# 2D array that looks like this
v = [[0, 0, 0],
    [1, 1, 1]]
v

[[0, 0, 0], [1, 1, 1]]

In [16]:
# creating array using of zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
# arrays filled with ones
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
# creating an empty array using the empty keyword, this works on random bases
# reason: speed, make sure you fill it later or afterwards
np.empty(2) # the result may vary

array([0.5, 1. ])

In [29]:
# creating array with range of numbers
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
# array with evenly spaced range
np.arange(59, 99, 4)

array([59, 63, 67, 71, 75, 79, 83, 87, 91, 95])

In [36]:
# creating an array with values that are spaced linearly in a specified interval
np.linspace(0, 10, num=5) # meaning i want 0 to 10 to produce 5 set of numbers but it should be within the range

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.linspace(4, 40, num=9)

array([ 4. ,  8.5, 13. , 17.5, 22. , 26.5, 31. , 35.5, 40. ])

In [41]:
# specifying datatype using the dtype keyword. The default datatype in numpy is float point
y = np.ones(3, dtype=np.int64)
y

array([1, 1, 1])

In [42]:
y.dtype

dtype('int64')

## Adding, removing, and sorting elements


In [45]:
# Sorting and element is simple with np.sort()
# the axis and order can be specified when the function is  called 
unsorted = np.sort([3, 2, 5, 9, 1, 45])
unsorted

array([ 1,  2,  3,  5,  9, 45])

# argsort: which is an indirect sort along a specified axis
# lexsort: which is an indirect stable sort on multiple keys
# searchsorted: which will find elements in sorted array, and 
# partition: which is a paritial sort

In [46]:
# concatenate
name_of_girls= ['Martha', 'Abigail']
name_of_boys = ['Archimedes', 'Ronaldo']
np.concatenate((name_of_girls, name_of_boys))

array(['Martha', 'Abigail', 'Archimedes', 'Ronaldo'], dtype='<U10')

In [48]:
# another way of concetenating is and this comes with axis
np.concatenate((name_of_girls, name_of_boys), axis=0)

array(['Martha', 'Abigail', 'Archimedes', 'Ronaldo'], dtype='<U10')

In [ ]:
# in order to remove elements from an array, its simple to use indexing to select the elements that you want to keep


In [57]:
# Reshaping an array
# this is done using the reshape keyword, which is a method
# Reshape means dealing with the rows and columns of an array
num = np.arange(6)

num

array([0, 1, 2, 3, 4, 5])

In [60]:
# reshape
num.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
a_.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [68]:
a_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
a_.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a_.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [75]:
# specifying a few optional parameters
#newshape is the new shape you want. You specify an integer or a tuple integers. If you specify an integer, 
#the result will be an array of that length


np.reshape(a, newshape=(1, 6), order='C')
# a is the array to be reshaped
# newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the
# result will be an array of that length. The shape should be compatible with the original shape.

# order: C means to read/write the elements using C-like index orde, F means to read/write the elements using 
# Fortran-like index order, A means to. read/write the elements in Fortran-like index order if a is a Fortran
# contiguous in memory, C-like order otherwise. This is an optional parameter and doesnt need to be specified


array([[1, 2, 3, 4, 5, 6]])

# How to convert a 1D array into a 2D array(how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [86]:
b = np.array([1, 3, 5, 6, 8, 9])
b.shape

(6,)

In [77]:
a.shape

(6,)

In [87]:
# adding new axis
b = b[np.newaxis, :]
b

array([[1, 3, 5, 6, 8, 9]])

In [88]:
b.shape

(1, 6)

In [89]:
# One can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.
# For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = b[np.newaxis, :]
row_vector.shape

(1, 1, 6)

In [90]:
#For column vector, you can insert an axis along the second dimension
column_vector = b[:, np.newaxis]
column_vector.shape

(1, 1, 6)

In [91]:
#expansion of an array can be done by inserting a new axis at a specified position with np.expand_dims
c = np.expand_dims(b, axis=1)

In [93]:
c.shape

(1, 1, 6)

In [94]:
# adding an axis at index positionof 0
c = np.expand_dims(b, axis=0)
c.shape

(1, 1, 6)

## INDEXING AND SLICING


In [96]:
arr = np.array([1, 2, 4, 5, 6])
arr

array([1, 2, 4, 5, 6])

In [97]:
arr[0]

1

In [99]:
arr[:]

array([1, 2, 4, 5, 6])

In [100]:
arr[-2]

5

In [101]:
arr[:3]

array([1, 2, 4])

In [102]:
arr[-2:]

array([5, 6])

In [103]:
arr[0:3]

array([1, 2, 4])

In [106]:
# If you want to select values from your array that fulfil certain conditions

d = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
print(d[d < 4])


[1 2 3]


In [109]:
# numbers that are equal and or greater than 10
print(d[d >= 10])

[10 11 12]


In [110]:
# select elements that are divisible by 2
print(d[d % 2 == 0])

[ 2  4  6  8 10 12]


In [111]:
# select elements that satisfy two conditions using the and and or operators
print(d[(d <=6) & (d % 2 == 0)])

[2 4 6]


In [112]:
# You can also make use of the logical operators & and | in order to 
#return boolean values that specify whether or not the 
#values in an array fulfill a certain condition. 
#This can be useful with arrays that contain names or other categorical values.

five_up = (d > 5) | (d == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [113]:
# use np.nonzero() to select elements or indices from an array
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
d.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [120]:
# indices of elements below 5
below_5 = d[d < 5]
below_5.nonzero()

(array([0, 1, 2, 3]),)

In [122]:
# another way of writing the same block of code
below = np.nonzero(d < 5)
below

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [123]:
list_of_coordinates = list(zip(d[0], d[1]))

for coord in list_of_coordinates:
    print(coord)

(1, 5)
(2, 6)
(3, 7)
(4, 8)
